services:
  - type: web
    name: rl-flask
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
